ci: reintroduce x86-64 test for non-SSE environment
The old CI test was removed
(https://github.com/BurntSushi/memchr/pull/77#issuecomment-1962389255)
due to https://github.com/rust-lang/rust/pull/116672
causing a mismatch of data layouts with the custom target
(`src/tests/x86_64-soft_float.json`):

```console
error: data-layout for target `x86_64-soft_float-10047705440633310713`, `e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128`, differs from LLVM target's `x86_64-unknown-none` default layout, `e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128`
```

This PR removes the unused custom target and reintroduces
the CI test with the now-available tier 2 target
[`x86_64-unknown-none`](https://doc.rust-lang.org/nightly/rustc/platfor
m-support/x86_64-unknown-none.html). This makes this test much more
robust, since we don't have to update a custom target ourselves and can
even use stable Rust now.

PR #146